/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1d13d1b7-68e2-4257-9a73-1a105b459dad",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bsaQMv0aV",
    "aws_user_pools_web_client_id": "1ru7n1v286rugmsv0flm5gg4ji",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bmrbml3bzvdm7i2lgava3mpsgu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "odws-20201010191626-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dbavvzs66ssnu.cloudfront.net"
};


export default awsmobile;
